name: OneWire Temperature Automatic Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/onewire_temperature/onewire_temperature_example.cpp
        target_device:
          - pioarduino_esp32
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install --upgrade platformio
      - name: Run PlatformIO
        run: ci/run-ci.sh
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          CI_TARGET_DEVICE: ${{ matrix.target_device }}
